// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Webonline.Data.EF;

namespace Webonline.Data.Migrations
{
    [DbContext(typeof(SchoolDbConnect))]
    [Migration("20210112082826_SeenData")]
    partial class SeenData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Webonline.Data.EF.Khoa", b =>
                {
                    b.Property<int>("IdKhoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasColumnName("TenKhoa")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("IdKhoa");

                    b.ToTable("KhoaSinhVien");

                    b.HasData(
                        new
                        {
                            IdKhoa = 123,
                            TenKhoa = "KhoaCNTT"
                        },
                        new
                        {
                            IdKhoa = 124,
                            TenKhoa = "KhoaCNSinhHoc"
                        },
                        new
                        {
                            IdKhoa = 125,
                            TenKhoa = "KhoaHoa"
                        });
                });

            modelBuilder.Entity("Webonline.Data.EF.MonHoc", b =>
                {
                    b.Property<int>("ID_Mon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdKhoa")
                        .HasColumnType("int");

                    b.Property<string>("Ten_MH")
                        .IsRequired()
                        .HasColumnName("TenMonHoc")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ID_Mon");

                    b.ToTable("MonHoc");

                    b.HasData(
                        new
                        {
                            ID_Mon = 345,
                            IdKhoa = 123,
                            Ten_MH = "Toan"
                        },
                        new
                        {
                            ID_Mon = 245,
                            IdKhoa = 123,
                            Ten_MH = "Van"
                        },
                        new
                        {
                            ID_Mon = 145,
                            IdKhoa = 125,
                            Ten_MH = "Hoa"
                        });
                });

            modelBuilder.Entity("Webonline.Data.EF.SinhVien", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdKhoa")
                        .HasColumnType("int");

                    b.Property<string>("MaSV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("IdKhoa");

                    b.ToTable("SinhViens");

                    b.HasData(
                        new
                        {
                            id = 1,
                            IdKhoa = 123,
                            MaSV = "12345",
                            Name = "Danh"
                        },
                        new
                        {
                            id = 2,
                            IdKhoa = 124,
                            MaSV = "123456",
                            Name = "Nam"
                        },
                        new
                        {
                            id = 3,
                            IdKhoa = 123,
                            MaSV = "1234",
                            Name = "Hung"
                        });
                });

            modelBuilder.Entity("Webonline.Data.Entities.MonHocKhoa", b =>
                {
                    b.Property<int>("KhoaID")
                        .HasColumnType("int");

                    b.Property<int>("MonhocID")
                        .HasColumnType("int");

                    b.HasKey("KhoaID", "MonhocID");

                    b.HasIndex("MonhocID");

                    b.ToTable("MonHocKhoa");
                });

            modelBuilder.Entity("Webonline.Data.Entities.Sinh_Mon", b =>
                {
                    b.Property<int>("Id_Mon")
                        .HasColumnType("int");

                    b.Property<int>("SinhvienId")
                        .HasColumnType("int");

                    b.HasKey("Id_Mon", "SinhvienId");

                    b.HasIndex("SinhvienId");

                    b.ToTable("MonHocSinhVien");

                    b.HasData(
                        new
                        {
                            Id_Mon = 345,
                            SinhvienId = 1
                        },
                        new
                        {
                            Id_Mon = 345,
                            SinhvienId = 2
                        },
                        new
                        {
                            Id_Mon = 345,
                            SinhvienId = 3
                        });
                });

            modelBuilder.Entity("Webonline.Data.EF.SinhVien", b =>
                {
                    b.HasOne("Webonline.Data.EF.Khoa", "Khoa")
                        .WithMany("SinhViens")
                        .HasForeignKey("IdKhoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Webonline.Data.Entities.MonHocKhoa", b =>
                {
                    b.HasOne("Webonline.Data.EF.Khoa", "Khoa")
                        .WithMany("MonHocKhoa")
                        .HasForeignKey("KhoaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Webonline.Data.EF.MonHoc", "monHoc")
                        .WithMany("MonHocKhoa")
                        .HasForeignKey("MonhocID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Webonline.Data.Entities.Sinh_Mon", b =>
                {
                    b.HasOne("Webonline.Data.EF.MonHoc", "MonHoc")
                        .WithMany("SinhMon")
                        .HasForeignKey("Id_Mon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Webonline.Data.EF.SinhVien", "SinhVien")
                        .WithMany("SinhMon")
                        .HasForeignKey("SinhvienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
