// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Webonline.Data.EF;

namespace Webonline.Data.Migrations
{
    [DbContext(typeof(SchoolDbConnect))]
    [Migration("20210112071020_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Webonline.Data.EF.Khoa", b =>
                {
                    b.Property<int>("IdKhoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasColumnName("TenKhoa")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("IdKhoa");

                    b.ToTable("KhoaSinhVien");
                });

            modelBuilder.Entity("Webonline.Data.EF.MonHoc", b =>
                {
                    b.Property<int>("ID_Mon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdKhoa")
                        .HasColumnType("int");

                    b.Property<string>("Ten_MH")
                        .IsRequired()
                        .HasColumnName("TenMonHoc")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ID_Mon");

                    b.ToTable("MonHoc");
                });

            modelBuilder.Entity("Webonline.Data.EF.SinhVien", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdKhoa")
                        .HasColumnType("int");

                    b.Property<string>("MaSV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("IdKhoa");

                    b.ToTable("SinhViens");
                });

            modelBuilder.Entity("Webonline.Data.Entities.MonHocKhoa", b =>
                {
                    b.Property<int>("KhoaID")
                        .HasColumnType("int");

                    b.Property<int>("MonhocID")
                        .HasColumnType("int");

                    b.HasKey("KhoaID", "MonhocID");

                    b.HasIndex("MonhocID");

                    b.ToTable("MonHocKhoa");
                });

            modelBuilder.Entity("Webonline.Data.Entities.Sinh_Mon", b =>
                {
                    b.Property<int>("Id_Mon")
                        .HasColumnType("int");

                    b.Property<int>("SinhvienId")
                        .HasColumnType("int");

                    b.HasKey("Id_Mon", "SinhvienId");

                    b.HasIndex("SinhvienId");

                    b.ToTable("MonHocSinhVien");
                });

            modelBuilder.Entity("Webonline.Data.EF.SinhVien", b =>
                {
                    b.HasOne("Webonline.Data.EF.Khoa", "Khoa")
                        .WithMany("SinhViens")
                        .HasForeignKey("IdKhoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Webonline.Data.Entities.MonHocKhoa", b =>
                {
                    b.HasOne("Webonline.Data.EF.Khoa", "Khoa")
                        .WithMany("MonHocKhoa")
                        .HasForeignKey("KhoaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Webonline.Data.EF.MonHoc", "monHoc")
                        .WithMany("MonHocKhoa")
                        .HasForeignKey("MonhocID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Webonline.Data.Entities.Sinh_Mon", b =>
                {
                    b.HasOne("Webonline.Data.EF.MonHoc", "MonHoc")
                        .WithMany("SinhMon")
                        .HasForeignKey("Id_Mon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Webonline.Data.EF.SinhVien", "SinhVien")
                        .WithMany("SinhMon")
                        .HasForeignKey("SinhvienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
